# Generated by Django 4.0.1 on 2022-01-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('variant_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=100)),
                ('feature', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_details', models.CharField(max_length=200)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.productvariants')),
            ],
        ),
    ]
