# Generated by Django 4.0.1 on 2022-01-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_productvariants_productspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='feature',
            field=models.CharField(max_length=200),
        ),
    ]
