# Generated by Django 4.0.1 on 2022-01-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='name',
            field=models.CharField(default='product name', max_length=100),
        ),
    ]
