# Generated by Django 4.0.1 on 2022-01-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_productvariants_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
