# Generated by Django 4.0.1 on 2022-01-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_productvariants_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='rating',
            field=models.CharField(choices=[('------', '-----'), ('Bad', 'bad'), ('Good', 'good'), ('Average', 'average'), ('Very Good', 'very good'), ('Excellent', 'excellent')], default='------', max_length=11),
        ),
    ]
