# Generated by Django 4.0.1 on 2022-01-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_productvariants_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='rating',
            field=models.CharField(choices=[('------', '-----'), ('Bad', 1), ('Good', 2), ('Average', 3), ('Very Good', 4), ('Excellent', 5)], max_length=11),
        ),
    ]
