# Generated by Django 4.0.1 on 2022-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_productvariants_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='rating',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=11),
        ),
    ]
